(() => {
  'use strict';
  const state = { page: document.body.dataset.page, allTools: [], creatorLookup: new Map(), favorites: JSON.parse(localStorage.getItem('aiTools:favorites')||'[]'), theme: localStorage.getItem('aiTools:theme') || 'light' };
  const $ = (s,r=document)=>r.querySelector(s);
  const escapeHtml=(v)=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
  const byCreatedDesc=(a,b)=>new Date(b.$createdAt)-new Date(a.$createdAt);
  function ensureLayer(){ if(!window.AppwriteLayer) throw new Error('AppwriteLayer not loaded. Ensure appwrite.js is included before script.js.'); }
  function getLogoUrl(link,size=96){ try{return `https://www.google.com/s2/favicons?domain=${new URL(link).hostname.replace(/^www\./,'')}&sz=${size}`;}catch{return './fallback.png';}}
  function creatorBadge(id){const a=state.creatorLookup.get(Number(id));if(!a?.length) return '';return `<div class="creator-pick-badge">⭐ Picked by <strong>${escapeHtml(a[0].name)}</strong>${a.length>1?` +${a.length-1} more`:''}</div>`;}
  function applyTheme(theme){const t=theme==='dark'?'dark':'light';state.theme=t;document.documentElement.setAttribute('data-theme',t);localStorage.setItem('aiTools:theme',t);const b=$('#themeToggle');if(b){b.textContent=t==='dark'?'☀️':'🌙';}}
  function initGlobal(){applyTheme(state.theme);$('#themeToggle')?.addEventListener('click',()=>applyTheme(state.theme==='dark'?'light':'dark'));$('#year')&&($('#year').textContent=new Date().getFullYear());$('#menuToggle')?.addEventListener('click',()=>$('#mainNav')?.classList.toggle('open'));document.addEventListener('scroll',()=>{const p=$('#scrollProgress'); if(!p) return; const h=document.documentElement.scrollHeight-window.innerHeight; p.style.width=`${h>0?(window.scrollY/h)*100:0}%`;},{passive:true});}
  function showPageSkeletons(){const sk='<div class="skeleton-card"></div><div class="skeleton-card"></div><div class="skeleton-card"></div><div class="skeleton-card"></div>';if(state.page==='index'){if($('#trendingGrid'))$('#trendingGrid').innerHTML=sk;if($('#categoryStats'))$('#categoryStats').innerHTML=sk;if($('#creatorPreviewStrip'))$('#creatorPreviewStrip').innerHTML=sk;}if(state.page==='list'&&$('#toolsGrid'))$('#toolsGrid').innerHTML=sk;if(state.page==='detailed'){if($('#toolDetails'))$('#toolDetails').innerHTML=sk;if($('#relatedTools'))$('#relatedTools').innerHTML=sk;}}
  function card(tool){return `<article class="tool-card"><div class="tool-card-top"><img class="tool-logo" src="${escapeHtml(getLogoUrl(tool.link))}" alt="${escapeHtml(tool.title)} logo" onerror="this.src='./fallback.png'"><div class="tool-card-meta"><a class="badge badge-link" href="category.html?name=${encodeURIComponent(tool.category)}">${escapeHtml(tool.category)}</a></div></div><h3>${escapeHtml(tool.title)}</h3><p class="description-2">${escapeHtml((tool.description||'').replace(/\[[^\]]+\]\(([^)]+)\)/g,'$1'))}</p>${creatorBadge(tool.id)}<div class="card-actions"><a class="btn btn-secondary" href="detailed.html?id=${tool.id}">View Details</a></div></article>`;}
  function animate(el,target){if(!el)return;const t0=performance.now();const d=1200;(function step(t){const p=Math.min((t-t0)/d,1);el.textContent=Math.floor(target*p).toLocaleString();if(p<1)requestAnimationFrame(step);})(t0);}
  async function initIndex(){
    let payload=null;
    try{const r=await fetch('./homepage.json',{cache:'no-store'}); if(r.ok) payload=await r.json();}catch{}
    if(payload?.featuredTools?.length){$('#trendingGrid').innerHTML=payload.featuredTools.slice(0,8).map(card).join('');animate($('#totalTools'),payload.stats?.totalTools||0);animate($('#totalCategories'),payload.stats?.totalCategories||0);$('#categoryStats').innerHTML=(payload.topCategories||[]).map((x)=>`<a class="category-pill category-link" href="category.html?name=${encodeURIComponent(x.category)}"><span>${escapeHtml(x.category)}</span><strong>${x.count}</strong></a>`).join('');}
    else {const [featured,stats]=await Promise.all([window.AppwriteLayer.fetchFeaturedTools(24),window.AppwriteLayer.fetchHomepageStats()]);$('#trendingGrid').innerHTML=featured.slice(0,8).map(card).join('');animate($('#totalTools'),stats.totalTools||0);animate($('#totalCategories'),stats.totalCategories||0);$('#categoryStats').innerHTML=(stats.topCategories||[]).map((x)=>`<a class="category-pill category-link" href="category.html?name=${encodeURIComponent(x.category)}"><span>${escapeHtml(x.category)}</span><strong>${x.count}</strong></a>`).join('');}
    const creators=await window.AppwriteLayer.fetchAllCreators();const strip=$('#creatorPreviewStrip');if(strip){strip.innerHTML='<div class="creator-mini skeleton"></div><div class="creator-mini skeleton"></div><div class="creator-mini skeleton"></div><div class="creator-mini skeleton"></div>';strip.innerHTML=creators.sort((a,b)=>(b.featured?1:0)-(a.featured?1:0)).slice(0,4).map(c=>`<a class="creator-mini" href="creators.html?slug=${c.slug||''}"><img src="${c.avatar_url||'fallback.png'}" alt="${escapeHtml(c.name)}"><span>${escapeHtml(c.name)}</span><small>${escapeHtml(c.platform||c.platforn||'Creator')} · ${((c.pick_ids||c.picks_ids||[]).length)} picks</small></a>`).join('')||'<p class="muted">No creators yet.</p>';}}
  async function initList(){const grid=$('#toolsGrid');if(!grid)return;grid.innerHTML='<div class="skeleton-card"></div><div class="skeleton-card"></div><div class="skeleton-card"></div><div class="skeleton-card"></div>';const sIn=$('#searchInput'),c=$('#categoryFilter'),o=$('#sortFilter');o.value='title-asc';let loaded=[],filtered=[],cursor=null,done=false,loading=false;const categories=new Set();
const applyFilter=()=>{filtered=[...loaded];if(sIn.value)filtered=filtered.filter(t=>t.title.toLowerCase().includes(sIn.value.toLowerCase()));if(c.value!=='all')filtered=filtered.filter(t=>t.category===c.value);if(o.value==='title-asc')filtered.sort((a,b)=>a.title.localeCompare(b.title));else if(o.value==='title-desc')filtered.sort((a,b)=>b.title.localeCompare(a.title));else if(o.value==='id-desc')filtered.sort(byCreatedDesc);else filtered.sort((a,b)=>-byCreatedDesc(a,b));grid.innerHTML=filtered.map(card).join('');$('#resultsCount').textContent=`${filtered.length} loaded`;};
const loadMore=async()=>{if(done||loading)return;loading=true;const loader=$('#infiniteLoader'); if(loader){loader.classList.remove('hidden'); loader.textContent='Loading more tools…';} const page=await window.AppwriteLayer.fetchToolsPage(50,cursor);loaded.push(...page.documents);page.documents.forEach(t=>categories.add(t.category));c.innerHTML='<option value="all">All categories</option>'+[...categories].sort().map(v=>`<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`).join('');cursor=page.nextCursor;done=!cursor;applyFilter();loading=false;const loader=$('#infiniteLoader'); if(loader){ if(done){loader.classList.remove('hidden'); loader.textContent='All tools loaded';} else {loader.classList.add('hidden');}}};
await loadMore();sIn.oninput=applyFilter;c.onchange=applyFilter;o.onchange=applyFilter;const sentinel=$('#listSentinel');if(sentinel){new IntersectionObserver((e)=>{if(e[0].isIntersecting)loadMore();},{rootMargin:'300px'}).observe(sentinel);} }
  async function initCategoryPage(){
    const params=new URLSearchParams(location.search); const category=params.get('name')||'';
    const title=$('#categoryTitle'), count=$('#categoryCount'), grid=$('#categoryGrid'), empty=$('#categoryEmpty');
    if(!category){ if(empty) empty.classList.remove('hidden'); return; }
    if(title) title.textContent=`${category} Tools`;
    const tools=await window.AppwriteLayer.fetchToolsByCategory(category,60);
    if(count) count.textContent=`${tools.length} tools in ${category}`;
    if(grid) grid.innerHTML=tools.map(card).join('');
    if(empty) empty.classList.toggle('hidden', tools.length>0);
  }
  async function initDetailed(){const id=Number(new URLSearchParams(location.search).get('id'));const tool=await window.AppwriteLayer.fetchToolById(id);if(!tool){$('#notFound')?.classList.remove('hidden');$('#relatedWrap')?.classList.add('hidden');return;}const prev=await window.AppwriteLayer.fetchToolById(id-1); const next=await window.AppwriteLayer.fetchToolById(id+1);$('#breadcrumb').innerHTML=`<a href="index.html">Home</a> &gt; <a href="category.html?name=${encodeURIComponent(tool.category)}">${escapeHtml(tool.category)}</a> &gt; <span>${escapeHtml(tool.title)}</span>`;const fav=state.favorites.includes(id);const ranks=await window.AppwriteLayer.fetchAllRanks();const rank=ranks.find(r=>Number(r.id)===id);const creators=state.creatorLookup.get(id)||[];$('#toolDetails').innerHTML=`<div class="detail-head"><img class="tool-logo tool-logo-lg" src="${getLogoUrl(tool.link,128)}" alt="${escapeHtml(tool.title)} logo"><div><h1>${escapeHtml(tool.title)}</h1><a class="badge badge-link" href="category.html?name=${encodeURIComponent(tool.category)}">${escapeHtml(tool.category)}</a></div></div><p>${escapeHtml(tool.description||'')}</p><div class="card-actions"><button class="btn btn-secondary ${fav?'fav-inline-active':''}" id="favoriteDetailBtn">${fav?'★':'☆'}</button><a class="btn btn-primary" href="${escapeHtml(tool.link)}" target="_blank" rel="noopener noreferrer">Visit Tool</a><a class="btn btn-secondary" href="list.html">Back to list</a></div><div class="tool-nav">${prev?`<a class="btn btn-secondary" href="detailed.html?id=${prev.id}">← ${escapeHtml(prev.title)}</a>`:''}${next?`<a class="btn btn-secondary" href="detailed.html?id=${next.id}">${escapeHtml(next.title)} →</a>`:''}</div>${rank?`<div class="detail-rank-card"><h3>📊 Rankings Score</h3><div class="rank-scores-row"><div class="rank-score-item"><span class="score-num">${rank.overall}</span><span class="score-lbl">Overall</span></div><div class="rank-score-item"><span class="score-num">${rank.reasoning}</span><span class="score-lbl">Reasoning</span></div><div class="rank-score-item"><span class="score-num">${rank.coding}</span><span class="score-lbl">Coding</span></div><div class="rank-score-item"><span class="score-num">${rank.vision}</span><span class="score-lbl">Vision</span></div><div class="rank-score-item"><span class="score-num">${parseInt(rank.context,10)||0}</span><span class="score-lbl">Context</span></div></div><a href="rankings.html" class="text-link">See full rankings →</a></div>`:''}${creators.length?`<div class="creator-endorsements"><h3>🎬 Creator Endorsed</h3>${creators.map(c=>`<a class="creator-chip" href="creators.html?slug=${c.slug}"><img src="${c.avatar_url}">${escapeHtml(c.name)}</a>`).join('')}</div>`:''}`;
$('#favoriteDetailBtn')?.addEventListener('click',()=>{state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[id,...state.favorites];localStorage.setItem('aiTools:favorites',JSON.stringify(state.favorites));initDetailed();});localStorage.setItem('mz_recently_viewed',JSON.stringify([{id:tool.id,title:tool.title,category:tool.category},...(JSON.parse(localStorage.getItem('mz_recently_viewed')||'[]').filter(x=>x.id!==tool.id))].slice(0,8)));const rel=(await window.AppwriteLayer.fetchToolsByCategory(tool.category,8)).filter(t=>Number(t.id)!==id).slice(0,4);$('#relatedTools').innerHTML=rel.length?rel.map(card).join(''):'<p class="muted">No related tools available.</p>';
  }
  (async()=>{initGlobal();showPageSkeletons();ensureLayer();if(state.page==='detailed'){state.creatorLookup=await window.AppwriteLayer.getCreatorPickLookup();}if(state.page==='index')await initIndex();if(state.page==='list')await initList();if(state.page==='detailed')await initDetailed();if(state.page==='category'&&typeof initCategoryPage==='function')initCategoryPage();})().catch((e)=>console.error(e));
})();
